import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from "react";


// configure it in your .env.local file
/*
* Example config
* const config = {
*  clientDisplayName, // the name of your app that you want the creators to see while granting access
*  environment, // the mode in which you want to use the SDK,  `sandbox` or `production`
*  userId, // the unique user_id parameter returned by Phyllo API when you create a user (see https://docs.getphyllo.com/docs/api-reference/reference/openapi.v1.yml/paths/~1v1~1users/post)
*  token,
*  redirect: false, // (optional) flag to indicate that you want to use the redirect flow, this is `false` by default
*  workPlatformId, // (optional) the unique work_platform_id of a specific work platform, if you want the creator to skip the platform selection screen and just be able to connect just with a single work platform
*};
*/

const configPhyllo = {
  clientDisplayName: "ExampleOrganization",
  environment: process.env.NEXT_PUBLIC_PHYLLO_SANDBOX_ENV,
  userId: process.env.NEXT_PUBLIC_PHYLLO_SANDBOX_USER_ID,
  token: process.env.NEXT_PUBLIC_PHYLLO_SANDBOX_SDK_TOKEN,
  redirect: true,
  redirectURL: "http://localhost:3000",
  workPlatformId: null,
};



const Home: NextPage = () => {
  const [phylloConnectSDK, setPhylloConnectSDK] = useState({});

  useEffect(() => {
    const PhylloConnect = window.PhylloConnect;
    const phylloConnect = PhylloConnect?.initialize(configPhyllo);
    console.log(phylloConnect)

    phylloConnect?.on(
      "accountConnected",
      (accountId: string, workplatformId: string, userId: string) => {
        console.log(
          `onAccountConnected: ${accountId}, ${workplatformId}, ${userId}`
        );
      }
    );
    phylloConnect?.on(
      "accountDisconnected",
      (accountId: string, workplatformId: string, userId: string) => {
        console.log(
          `onAccountDisconnected: ${accountId}, ${workplatformId}, ${userId}`
        );
      }
    );
    phylloConnect?.on("tokenExpired", (userId: string) => {
      console.log(`onTokenExpired: ${userId}`);
    });
    phylloConnect?.on("exit", (reason: string, userId: string) => {
      console.log(`onExit: ${reason}, ${userId}`);
    });
    phylloConnect?.on("connectionFailure", (reason: string, workplatformId: string, userId: string) => {
      console.log(
        `onConnectionFailure: ${reason}, ${workplatformId}, ${userId}`
      );
    });
    setPhylloConnectSDK(phylloConnect);
  }, []);

  const redirectToPhylloSDK = () => {
    phylloConnectSDK?.open();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://cdn.getphyllo.com/connect/v2/phyllo-connect.js"></script>
      </Head>
    

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <button onClick={redirectToPhylloSDK}>
          Click me to go to Phyllo sdk
        </button>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
