import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from "react";

// configure it in your .env.local file
const config = {
  clientDisplayName: "MintersLabs",
  environment: "production",
  userId: process.env.NEXT_PUBLIC_PHYLLO_SANDBOX_CLIENT_ID,
  token: process.env.NEXT_PUBLIC_PHYLLO_SANDBOX_SDK_TOKEN,
  redirect: "popup",
  workPlatformId: "null",
};

// configure it in your .env file
const configPhyllo = {
  clientDisplayName: "MintersLabs",
  environment: "sandbox",
  userId: "606df955-c81f-450c-8988-9cf3b24a6343",
  token: process.env.NEXT_PUBLIC_PHYLLO_SANDBOX_SDK_TOKEN,
  redirect: true,
  redirectURL: "http://localhost:3000"
};



const Home: NextPage = () => {
  const [phylloConnectSDK, setPhylloConnectSDK] = useState({});

  useEffect(() => {
    const PhylloConnect = window.PhylloConnect;
    const phylloConnect = PhylloConnect?.initialize(configPhyllo);

    phylloConnect?.on(
      "accountConnected",
      (accountId, workplatformId, userId) => {
        console.log(
          `onAccountConnected: ${accountId}, ${workplatformId}, ${userId}`
        );
      }
    );
    phylloConnect?.on(
      "accountDisconnected",
      (accountId, workplatformId, userId) => {
        console.log(
          `onAccountDisconnected: ${accountId}, ${workplatformId}, ${userId}`
        );
      }
    );
    phylloConnect?.on("tokenExpired", (userId) => {
      console.log(`onTokenExpired: ${userId}`);
    });
    phylloConnect?.on("exit", (reason, userId) => {
      console.log(`onExit: ${reason}, ${userId}`);
    });
    phylloConnect?.on("connectionFailure", (reason, workplatformId, userId) => {
      console.log(
        `onConnectionFailure: ${reason}, ${workplatformId}, ${userId}`
      );
    });
    setPhylloConnectSDK(phylloConnect);
  }, []);

  const redirectToPhylloSDK = () => {
    phylloConnectSDK?.open();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://cdn.getphyllo.com/connect/v2/phyllo-connect.js"></script>
      </Head>
    

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <button onClick={redirectToPhylloSDK}>
          Click me to go to Phyllo sdk
        </button>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
